// <auto-generated />
namespace BusinessLogic.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDraftFieldToFileset : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDraftFieldToFileset));
        
        string IMigrationMetadata.Id
        {
            get { return "201303190203421_AddDraftFieldToFileset"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
